"""add bitrix_id to applications

Revision ID: 7af7d0b0759c
Revises: c1d2e3f4a5b6
Create Date: 2026-06-16 12:32:16.539103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af7d0b0759c'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('bitrix_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_applications_bitrix_id'), 'applications', ['bitrix_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_bitrix_id'), table_name='applications')
    op.drop_column('applications', 'bitrix_id')
    # ### end Alembic commands ###
